# Actividad 02 Joaquin Leon Martinez

## 1. Dado un conjunto de 30 datos de test, con la variable objetivo real y la salida proporcionada por dos modelos.

### 1.1 Calcular las métricas de regresión para cada modelo.

In [20]:
import pandas as pd
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
import math

# Lo primero es cargar los datos
df1 = pd.read_csv("l2p1.csv")

# Mostramos
df1.head()

Y objetivo  Predicciones M1  Predicciones M2
0        2.50              3.0              2.0
1        3.00              2.9              2.0
2        1.60              2.0              2.0
3        8.00              8.1              7.0
4        4.56              4.0              5.0

#### 1.1.1  MAE (Error Absoluto Medio)



Es la diferencia entre el valor pronosticado y el valor real en cada punto pronosticado, conceptualmente la métrica de evaluación más fácil para problemas de regresión. Responde a la pregunta: "¿En qué medida te equivocaste en tus predicciones, en promedio?"


Para comprenderlo mejor tomemos el siguiente ejemplo: consideremos que estamos pronosticando los precios de vehículos usados. El precio real de un vehículo usado es de 10k. Después de aplicar un modelo de Machine Learning predijimos que el precio es de 12k, ahora podemos observar que la diferencia es de 2k entre ambos precios de venta. Esta diferencia se llama error absoluto. 


(Δ y) = | y i — ŷ |

y i : representa el valor real

ŷ : representa el valor predicho

El caso anterior representa el error absoluto para una sola observación. Pero en la práctica tendremos muchos datos para predecir la salida. Por lo tanto, usamos para obtener el error absoluto medio (MAE), es decir, la media de los errores absolutos de toda la observación.


Ventajas de MAE:

- Es una métrica de evaluación fácil de calcular.
- Todos los errores se ponderan en la misma escala ya que se toman valores absolutos.
- Es útil si los datos de entrenamiento tienen valores atípicos, ya que MAE no penaliza los errores elevados causados por los valores atípicos.
- Proporciona una medida uniforme de qué tan bien está funcionando el modelo.


Desventajas de MAE

- MAE sigue una medida de precisión dependiente de la escala en la que utiliza la misma escala que los datos que se están midiendo. Por lo tanto, no puede usarse para comparar series usando diferentes medidas.
- Una de las principales desventajas de MAE es que no es diferenciable en cero. Muchos algoritmos de optimización tienden a utilizar la diferenciación para encontrar el valor óptimo de los parámetros en la métrica de evaluación.
- Puede ser un desafío calcular gradientes en MAE.

In [10]:
# Procedemos a calcular MAE:

# MAE para el Modelo 1
# Necesitamos obtener el numero de elementos que hay en el df1
num_elementos = df1.shape[0]
#print(num_elementos)

# Calcular la diferencia en valor absoluto entre todos los valores de la primera y la segunda columna
dif_abs = (df1['Y objetivo'] - df1['Predicciones M1']).abs()
#print(dif_abs)

# Calculamos el MAE
MAE_M1 = dif_abs.sum()/num_elementos

# Comparamos con el que calcula pandas
MAE_M1_PD = mean_absolute_error(df1['Y objetivo'], df1['Predicciones M1'])

print("MAE calculado por nosotros: ", MAE_M1 )
print("MAE calculado por pandas: ", MAE_M1_PD )

MAE calculado por nosotros:  1.0396666666666667
MAE calculado por pandas:  1.0396666666666667


In [11]:
# MAE para el Modelo 2
# Calcular la diferencia en valor absoluto entre la primera y la tercera columna
dif_abs2 = (df1['Y objetivo'] - df1['Predicciones M2']).abs()
#print(dif_abs)

# Calculamos el MAE
MAE_M2 = dif_abs2.sum()/num_elementos

# Comparamos con el que calcula pandas
MAE_M2_PD = mean_absolute_error(df1['Y objetivo'], df1['Predicciones M2'])

print("MAE calculado por nosotros: ", MAE_M2 )
print("MAE calculado por pandas: ", MAE_M2_PD )

MAE calculado por nosotros:  0.6113333333333333
MAE calculado por pandas:  0.6113333333333333


#### 1.1.2 MSE (Error cuadrático medio)

MSE básicamente mide el error cuadrado promedio de nuestras predicciones. Para cada punto, calcula la diferencia cuadrada entre las predicciones y el objetivo y luego promedia esos valores.

Cuanto mayor sea este valor, peor es el modelo. Nunca es negativo, ya que estamos cuadrando los errores de predicción individuales antes de sumarlos, pero sería cero para un modelo perfecto.

Ventaja:
- Útil si tenemos valores inesperados que nos deberían interesar. Muy alto o bajo valor que debemos prestar atención.

Desventajas:
- Si hacemos una predicción muy mala, la cuadratura empeorará aún más el error y puede sesgar la métrica para sobreestimar la maldad del modelo. Este es un comportamiento particularmente problemático si tenemos datos ruidosos (es decir, los datos que por cualquier motivo no son del todo confiables).
- Incluso un modelo “perfecto” puede tener un MSE alto en esa situación. Por lo que es difícil juzgar qué tan bien modelo está realizando.
- Por otro lado, si todos los errores son pequeños, o más bien, más pequeños que 1, se siente el efecto contrario: podemos subestimar la maldad del modelo.

In [16]:
# Procedemos a calcular MSE:

# MSE para el Modelo 1
# Necesitamos obtener el numero de elementos que hay en el df1
num_elementos = df1.shape[0]
#print(num_elementos)

# diferencia en valor absoluto entre todos los valores de la primera y la segunda columna Y ESTA VEZ SE ELEVA AL CUADRADO
dif_abs = (df1['Y objetivo'] - df1['Predicciones M1'])**2
#print(dif_abs)

# Calculamos el MAE
MSE_M1 = dif_abs.sum()/num_elementos

# Comparamos con el que calcula pandas
MSE_M1_PD = mean_squared_error(df1['Y objetivo'], df1['Predicciones M1'])

print("MSE calculado por nosotros: ", MSE_M1 )
print("MSE calculado por pandas: ", MSE_M1_PD )

MSE calculado por nosotros:  7.9830499999999995
MSE calculado por pandas:  7.9830499999999995


In [18]:
MSE_M2 = ((df1['Y objetivo'] - df1['Predicciones M2'])**2).sum()/num_elementos

# Comparamos con el que calcula pandas
MSE_M2_PD = mean_squared_error(df1['Y objetivo'], df1['Predicciones M2'])

print("MSE calculado por nosotros: ", MSE_M2 )
print("MSE calculado por pandas: ", MSE_M2_PD )

MSE calculado por nosotros:  0.5219533333333334
MSE calculado por pandas:  0.5219533333333334


#### 1.1.2 RMSE (Root Mean Squared Error)

RMSE es solo la raíz cuadrada de MSE. La raíz cuadrada se introduce para hacer que la escala de los errores sea igual a la escala de los objetivos.

In [21]:
# Procedemos a calcular el RMSE

RMSE_M1 = math.sqrt(MSE_M1)

print("RMSE_M1 calculado: ", RMSE_M1)

RMSE_M1 calculado:  2.8254291709402306


In [22]:
# Lo mismo con el segundo mmodelo:
RMSE_M2 = math.sqrt(MSE_M2)

print("RMSE_M2 calculado: ", RMSE_M2)

RMSE_M2 calculado:  0.7224633785413164


### 1.2 En función de los resultados, decidir qué modelo es mejor.

Basandonos en que todas las metricas de regresión calculadas tienen valores menores para el modelo 2, podemos afirmar que el segundo modelo es mejor.

## 2. Dado un problema de clasificación binaria (sólo existen dos clases), tenemos la salida de cada uno de 30 patrones en test para dos modelos distintos.

In [31]:
# Imports:
from sklearn.metrics import confusion_matrix
import numpy as np

In [23]:
# Lo primero es cargar los datos
df2 = pd.read_csv("l2p2.csv")

# Mostramos
df2.head()

Clase Objetivo  Predicciones M1  Predicciones M2
0               0                1                0
1               0                0                0
2               0                0                0
3               1                1                1
4               1                1                1

### 2.1 Montar la matriz de confusión de cada modelo.

In [33]:
# Calcular la matriz de confusión:

# Calculammos TP (True positives)
TP1 = ((df2['Clase Objetivo'] == 0) & (df2['Predicciones M1'] == 0)).sum()
# Calculammos FN (False negatives)
FN1 = ((df2['Clase Objetivo'] == 0) & (df2['Predicciones M1'] == 1)).sum()
# Calculammos FP (False positives)
FP1 = ((df2['Clase Objetivo'] == 1) & (df2['Predicciones M1'] == 0)).sum()
# Calculammos TN (True negatives)
TN1 = ((df2['Clase Objetivo'] == 1) & (df2['Predicciones M1'] == 1)).sum()

# Montamos la matriz
CM1 = np.array([[TP1, FN1], 
       [FP1, TN1]])

# La calculamos tambbien con la libreria:
clases = df2['Clase Objetivo'].unique()
CM1_PD = confusion_matrix(df2['Clase Objetivo'], df2['Predicciones M1'], labels=clases)

# Mostramos resultados
print("Matriz de confusión calculada:")
print(CM1)

print("Matriz de confusión de pandas:")
print(CM1_PD)

Matriz de confusión calculada:
[[19  1]
 [ 4  6]]
Matriz de confusión de pandas:
[[19  1]
 [ 4  6]]


In [34]:
# Calcular la matriz de confusión para el segundo modelo

# Calculammos TP (True positives)
TP2 = ((df2['Clase Objetivo'] == 0) & (df2['Predicciones M2'] == 0)).sum()
# Calculammos FN (False negatives)
FN2 = ((df2['Clase Objetivo'] == 0) & (df2['Predicciones M2'] == 1)).sum()
# Calculammos FP (False positives)
FP2 = ((df2['Clase Objetivo'] == 1) & (df2['Predicciones M2'] == 0)).sum()
# Calculammos TN (True negatives)
TN2 = ((df2['Clase Objetivo'] == 1) & (df2['Predicciones M2'] == 1)).sum()

# Montamos la matriz
CM2 = np.array([[TP2, FN2], 
       [FP2, TN2]])

# La calculamos tambbien con la libreria:
clases = df2['Clase Objetivo'].unique()
CM2_PD = confusion_matrix(df2['Clase Objetivo'], df2['Predicciones M2'], labels=clases)

# Mostramos resultados
print("Matriz de confusión calculada:")
print(CM2)

print("Matriz de confusión de pandas:")
print(CM2_PD)

Matriz de confusión calculada:
[[12  8]
 [ 1  9]]
Matriz de confusión de pandas:
[[12  8]
 [ 1  9]]


### 2.2 Calcular las métricas de clasificación, excepto el AUC.

#### 2.2.1 CCR (Precision Global): Porcentaje de patrones correctamente clasificados

In [38]:
# CCR Modelo 1

# Numero total de elementos:
N = df2.shape[0]

CCR_M1 = (TP1 + TN1)/N

print(CCR_M1)

0.8333333333333334


In [39]:
# CCR Modelo 2

CCR_M2 = (TP2 + TN2)/N

print(CCR_M2)

0.7


#### 2.2.2 Sensibilidad (Recall o TP Rate): Porcentaje de patrones positivos predichos como positivos

In [40]:
# Sensibilidad Modelo 1

TPR_M1 = TP1/(TP1+FN1)

print(TPR_M1)

0.95


In [41]:
# Sensibilidad Modelo 2

TPR_M2 = TP2/(TP2+FN2)

print(TPR_M2)

0.6


#### 2.2.3 False Positive Rate (FP Rate): Porcentaje de patrones negativos predichos como positivos

In [42]:
# FPR Modelo 1

FPR_M1 = FP1/(TN1+FP1)

print(FPR_M1)

0.4


In [43]:
# FPR Modelo 2

FPR_M2 = FP2/(TN2+FP2)

print(FPR_M2)

0.1


In [44]:
# Precision Modelo 1

ACC_M1 = TP1/(TP1+FP1)

print(ACC_M1)

0.8260869565217391


In [45]:
# Precision Modelo 2

ACC_M2 = TP2/(TP2+FP2)

print(ACC_M2)

0.9230769230769231


In [47]:
# F1-Score Modelo 1

F1Score_M1 = (2*ACC_M1*TPR_M1)/(ACC_M1+TPR_M1)
print(F1Score_M1)

0.8837209302325583


In [48]:
# F1-Score Modelo 2

F1Score_M2 = (2*ACC_M2*TPR_M2)/(ACC_M2+TPR_M2)
print(F1Score_M2)

0.7272727272727274


### 2.3 Determinar qué modelo es mejor.

En base a los datos obtenidos podemos determinar que el modelo 2 es mejor que el modelo 1, en este caso no hay una diferencia tan significativa como en el ejercicio anterior.