# Actividad 03 Joaquin Leon Martinez

# 3.1 Regresion

Se desea estimar el valor 𝑌 de una casa dada su superficie 𝑋1 y el número de habitaciones 𝑋2. 

In [2]:
# Cargamos las librerias necesarias
import pandas as pd
import numpy as np

In [6]:
# Cargamos los datos

# Actividad 3.1
df1_train = pd.read_csv('l3p1_train.csv')
df1_test = pd.read_csv('l3p1_test.csv')

# Actividad 3.2
df2_test = pd.read_csv('l3p2_test.csv')

# Actividad3.3
df3_train = pd.read_csv('l3p3_train.csv')
df3_test = pd.read_csv('l3p3_test.csv')

## 3.1.1. El modelo de regresión lineal simple de 𝑌 en función de 𝑋1.

In [7]:
# Para los modelos de regresion lineal se recomienda escalar las variables antes de comenzar con el entrenamiento.
# Escalar un modelo: tomar su valor minimo como 0 y el maximmo como 1, el resto seran numeros comprendidos entre 0  1

# Comprobammos los datos antes de escalar:
df1_train.head()

x1  x2    y
0  60   1  120
1  55   2  125
2  70   1  130
3  60   2  112
4  62   1  122

In [8]:
# Procedemos a escalarlo (sin utilizar sklearn):
# Guardamos el nombre de la columna que queremos escalara en una variable
columna = 'x1'

# Almacenamos los valores mínimos y máximos de la columna
min_valor = df1_train[columna].min()
max_valor = df1_train[columna].max()

# Escalamos la columna utilizando la fórmula de min-max scaling
df1_train[columna] = (df1_train[columna] - min_valor) / (max_valor - min_valor)
df1_train.head()

x1  x2    y
0  0.166667   1  120
1  0.000000   2  125
2  0.500000   1  130
3  0.166667   2  112
4  0.233333   1  122

In [9]:
# Hacemos lo mmismmmo con la columna x2 (para dejarla lista para el siguiente ejercicio)
columna = 'x2'
min_valor = df1_train[columna].min()
max_valor = df1_train[columna].max()
df1_train[columna] = (df1_train[columna] - min_valor) / (max_valor - min_valor)
df1_train.head(10)

x1   x2    y
0  0.166667  0.0  120
1  0.000000  0.5  125
2  0.500000  0.0  130
3  0.166667  0.5  112
4  0.233333  0.0  122
5  0.500000  0.5  135
6  0.166667  1.0  128
7  0.833333  0.0  140
8  0.833333  0.5  150
9  1.000000  1.0  160

In [10]:
# Ahora calcularemos las medias de todas las columnas: (las utilizaremmos mas tardes para optiizar el modelo)
meanx1 = df1_train['x1'].mean()
meanx2 = df1_train['x2'].mean()
meany = df1_train['y'].mean()

print('Las medias de x1, x2 e y son ', meanx1, meanx2, meany, ' respectivamente')

Las medias de x1, x2 e y son  0.44000000000000006 0.4 132.2  respectivamente


In [11]:
# Calculammos la matriz de varianza-covarianza:
# Para calcularla necesitaremos primero las varianzas de todas las variables
varx1 = df1_train['x1'].var()
varx2 = df1_train['x2'].var()
vary = df1_train['y'].var()

# Calculammos tambien las covarianzas
covyx1 = df1_train['y'].cov(df1_train['x1'])
covyx2 = df1_train['y'].cov(df1_train['x2'])
covx1x2 = df1_train['x1'].cov(df1_train['x2'])

'''
La matriz de covarianza debe quedar tal que asi:
vary covyx1 covyx2
covyx1 varx1 covx1x2
covyx2 covx1x2 varx2
'''

m_cov = np.array([[vary, covyx1, covyx2],
                               [covyx1, varx1, covx1x2],
                               [covyx2, covx1x2, varx2]])

print("Matriz de Covarianzas:")
print(m_cov)


Matriz de Covarianzas:
[[2.10400000e+02 4.55037037e+00 2.24444444e+00]
 [4.55037037e+00 1.21185185e-01 1.74074074e-02]
 [2.24444444e+00 1.74074074e-02 1.55555556e-01]]


In [12]:
# Probammos a calcular la mariz de covarianza con numpy
data = np.array([
    [120, 0.166667, 0.0],
    [125, 0.000000, 0.5],
    [130, 0.500000, 0.0],
    [112, 0.166667, 0.5],
    [122, 0.233333, 0.0],
    [135, 0.500000, 0.5],
    [128, 0.166667, 1.0],
    [140, 0.833333, 0.0],
    [150, 0.833333, 0.5],
    [160, 1.000000, 1.0]
])



# Calcula la matriz de varianza-covarianza (es la misma que la matriz de covarianza)
var_cov_matrix = np.cov(data.T)

print("Matriz de Varianza-Covarianza con la tercera columna en la primera posición:")
print(var_cov_matrix)

Matriz de Varianza-Covarianza con la tercera columna en la primera posición:
[[2.10400000e+02 4.55036844e+00 2.24444444e+00]
 [4.55036844e+00 1.21185081e-01 1.74074444e-02]
 [2.24444444e+00 1.74074444e-02 1.55555556e-01]]


In [13]:
# En este caso queremos calcular la regresion lineal de y en funcion de x1
# Por lo tanto tenemmos que calcular B0 y B1 en la siguiente formula: y = B0 + B1*x1
# Commo hemos visto en clase B1 = covyx1/varx1 
B1 = covyx1/varx1

print('B1 = ', B1)

B1 =  37.54889975550122


In [14]:
# B0 = meany - B1*meanx1
B0 = meany - B1*meanx1
print('B0 = ', B0)

B0 =  115.67848410757945


In [15]:
# Por lo tanto el modelo de regresion lineal en este caso seria -414.88190709046427 + 1243.3679706601458*x1

# Vamos a ver que resultados obtenemos: y = B0 + B1*X1 
df1_train['y_pred'] = B0 + B1 * df1_train['x1']

print(df1_train)

         x1   x2    y      y_pred
0  0.166667  0.0  120  121.936634
1  0.000000  0.5  125  115.678484
2  0.500000  0.0  130  134.452934
3  0.166667  0.5  112  121.936634
4  0.233333  0.0  122  124.439894
5  0.500000  0.5  135  134.452934
6  0.166667  1.0  128  121.936634
7  0.833333  0.0  140  146.969234
8  0.833333  0.5  150  146.969234
9  1.000000  1.0  160  153.227384


## 3.1.2. El modelo de regresión lineal simple de 𝑌 en función de 𝑋2.

In [16]:
# Seguios el mismo procedimiento que en el caso anterior pero con x2

# En este caso queremos calcular la regresion lineal de y en funcion de x2
# Por lo tanto tenemmos que calcular B0 y B1 en la siguiente formula: y = B0 + B1*x2
# Commo hemos visto en clase B1 = covyx2/varx2 
B1 = covyx2/varx2
# B0 = meany - B1*meanx1
B0 = meany - B1*meanx2
print('B0 = ', B0)
print('B1 = ', B1)


B0 =  126.42857142857142
B1 =  14.428571428571423


In [17]:
# Por lo tanto el modelo de regresion lineal en este caso seria -414.88190709046427 + 1243.3679706601458*x2

# Vamos a ver que resultados obtenemos: y = B0 + B1*X1 
df1_train['y2_pred'] = B0 + B1 * df1_train['x2']

print(df1_train)

         x1   x2    y      y_pred     y2_pred
0  0.166667  0.0  120  121.936634  126.428571
1  0.000000  0.5  125  115.678484  133.642857
2  0.500000  0.0  130  134.452934  126.428571
3  0.166667  0.5  112  121.936634  133.642857
4  0.233333  0.0  122  124.439894  126.428571
5  0.500000  0.5  135  134.452934  133.642857
6  0.166667  1.0  128  121.936634  140.857143
7  0.833333  0.0  140  146.969234  126.428571
8  0.833333  0.5  150  146.969234  133.642857
9  1.000000  1.0  160  153.227384  140.857143


## 3.1.3. El modelo de regresión lineal múltiple de 𝑌 en función de 𝑋1 y 𝑋2.

In [18]:
# Aqui se nos complican un poco las ecuaciones porque teneos dos variables. la formula pasa a ser y = B0 + B1*x1 + B2*x2
# B0 = meany - B1*meanx1 - B2*meanx2
# B1 = -A12 / -A11
# B2 = -A13 / - A11

# Antes de continuar necesitareos llos adjuntos para calcular lo anterior
varx1 = df1_train['x1'].var()
varx2 = df1_train['x2'].var()
vary = df1_train['y'].var()

# Calculammos tambien las covarianzas
covyx1 = df1_train['y'].cov(df1_train['x1'])
covyx2 = df1_train['y'].cov(df1_train['x2'])
covx1x2 = df1_train['x1'].cov(df1_train['x2'])

A12 = - ((covyx1 * varx2) - (covx1x2 * covyx2)) # Este se niega porque la suma de los subindices da impar
A11 = ((varx1 * varx2) - (covx1x2 * covx1x2))
A13 = ((covyx1 * covx1x2) - (varx1 * covyx2))

# Ahora si que podemos calcular la formmula:
B1 = -A12 / A11
B2 = -A13 / A11
B0 = meany - B1*meanx1 - B2*meanx2

print('B0 = ', B0)
print('B1 = ', B1)
print('B2 = ', B2)

B0 =  112.17790186000073
B1 =  36.05591095662463
B2 =  10.39374329771105


In [19]:
# Comprobamos que tal es:
# Por lo tanto el modelo de regresion lineal en este caso seria -414.88190709046427 + 1243.3679706601458*x1

# Vamos a ver que resultados obtenemos: y = B0 + B1*X1 
df1_train['y_pred3'] = B0 + B1 * df1_train['x1'] + B2 * df1_train['x2']

print(df1_train)

         x1   x2    y      y_pred     y2_pred     y_pred3
0  0.166667  0.0  120  121.936634  126.428571  118.187220
1  0.000000  0.5  125  115.678484  133.642857  117.374774
2  0.500000  0.0  130  134.452934  126.428571  130.205857
3  0.166667  0.5  112  121.936634  133.642857  123.384092
4  0.233333  0.0  122  124.439894  126.428571  120.590948
5  0.500000  0.5  135  134.452934  133.642857  135.402729
6  0.166667  1.0  128  121.936634  140.857143  128.580964
7  0.833333  0.0  140  146.969234  126.428571  142.224494
8  0.833333  0.5  150  146.969234  133.642857  147.421366
9  1.000000  1.0  160  153.227384  140.857143  158.627556


## 3.1.4. Validar cada modelo con el siguiente conjunto de test.

In [30]:
# Importante no olvidarse de escalar los datos de test utilizando el maximo y el minimo del conjunto de entrenamiento
df1_train_original = pd.read_csv('l3p1_train.csv')

columna = 'x1'
min_valor = df1_train_original[columna].min()
max_valor = df1_train_original[columna].max()
df1_test[columna] = (df1_test[columna] - min_valor) / (max_valor - min_valor)

columna = 'x2'
min_valor = df1_train_original[columna].min()
max_valor = df1_train_original[columna].max()
df1_test[columna] = (df1_test[columna] - min_valor) / (max_valor - min_valor)

df1_test.head()

x1   x2    y
0  0.100000  0.0  120
1 -0.166667  1.0  128
2  0.833333  0.0  140
3  0.333333  0.5  115
4  0.000000  0.0  120

In [31]:
B1 = covyx1/varx1
B0 = meany - B1*meanx1
df1_test['y2_pred1'] = B0 + B1 * df1_test['x1']

print(df1_test)

         x1   x2    y    y2_pred1
0  0.100000  0.0  120  119.433374
1 -0.166667  1.0  128  109.420334
2  0.833333  0.0  140  146.969234
3  0.333333  0.5  115  128.194784
4  0.000000  0.0  120  115.678484
5  0.666667  0.5  145  140.711084
6  0.000000  1.0  125  115.678484
7  0.833333  1.0  170  146.969234
8  0.500000  0.0  135  134.452934
9  0.666667  1.0  155  140.711084


In [32]:
B1 = covyx2/varx2
B0 = meany - B1*meanx2
df1_test['y2_pred2'] = B0 + B1 * df1_test['x2']

print(df1_test)

         x1   x2    y    y2_pred1    y2_pred2
0  0.100000  0.0  120  119.433374  126.428571
1 -0.166667  1.0  128  109.420334  140.857143
2  0.833333  0.0  140  146.969234  126.428571
3  0.333333  0.5  115  128.194784  133.642857
4  0.000000  0.0  120  115.678484  126.428571
5  0.666667  0.5  145  140.711084  133.642857
6  0.000000  1.0  125  115.678484  140.857143
7  0.833333  1.0  170  146.969234  140.857143
8  0.500000  0.0  135  134.452934  126.428571
9  0.666667  1.0  155  140.711084  140.857143


In [33]:
# Una vez escalados los datos vamos a probarlo:
# Vamos a ver que resultados obtenemos: y = B0 + B1*X1 
df1_test['y_pred3'] = B0 + B1 * df1_test['x1'] + B2 * df1_test['x2']

print(df1_test)

         x1   x2    y    y2_pred1    y2_pred2     y_pred3
0  0.100000  0.0  120  119.433374  126.428571  127.871429
1 -0.166667  1.0  128  109.420334  140.857143  134.417553
2  0.833333  0.0  140  146.969234  126.428571  138.452381
3  0.333333  0.5  115  128.194784  133.642857  136.434967
4  0.000000  0.0  120  115.678484  126.428571  126.428571
5  0.666667  0.5  145  140.711084  133.642857  141.244491
6  0.000000  1.0  125  115.678484  140.857143  136.822315
7  0.833333  1.0  170  146.969234  140.857143  148.846124
8  0.500000  0.0  135  134.452934  126.428571  133.642857
9  0.666667  1.0  155  140.711084  140.857143  146.441362


In [ ]:
# Se puede observar que todos se hacercan en mayor o menor medida a la salida esperada

# 3.2 Regresión Logística Múltiple

Haciendo uso de la base de datos Iris vista anteriormente, se ha ejecutado un algoritmo para estimar los parámetros de una regresión logística múltiple. Como el problema tiene tres clases: setosa (1), versicolor (2) y virgínica (3), se han generado los dos modelos siguientes: 

𝑓1(𝑿,𝛽1)=541.0741 – 33.121𝑋1−10.2824𝑋2−38.5734𝑋3−90.4374𝑋4
𝑓2(𝑿,𝜷𝟐)=501.1562−26.3497𝑋1−24.2689𝑋2−10.7613𝑋3−130.0915𝑋4

## 3.2.1. Hallar las predicciones del modelo para el siguiente conjunto de test.

In [25]:
df2_test = pd.read_csv('l3p2_test.csv')
df2_test.head()

x1   x2   x3   x4  clase
0  4.6  3.2  1.4  0.2      1
1  5.3  3.7  1.5  0.2      1
2  5.7  4.4  1.5  0.4      1
3  5.0  3.5  1.6  0.6      2
4  5.5  2.5  4.0  1.3      2

In [28]:
# Para el modelo 1:
ef1 = np.exp(541.0741 - 33.121 * df2_test['x1'] -  10.2824 * df2_test['x2'] - 38.5734 * df2_test['x3'] - 90.4374 * df2_test['x4'])

# Para el modelo 2:
ef2 = np.exp(501.1562 - 26.3497 * df2_test['x1'] -  24.2689 * df2_test['x2'] - 10.7613 * df2_test['x3'] - 130.0915 * df2_test['x4'])


#ef3 = 1 - (ef1 + ef2)

sumatorio = ef1 + ef2 #+ ef3

# Calculamos la probabilidad de que sea clase 1: e^f1 / 1 + sumatorio(e^f)
pf1 = ef1 / (1 + sumatorio)

# Lo mismo para la clase 2
pf2 = ef2 / (1 + sumatorio)

# Para la clase 3 (solo hay 3 clases de flores) seria 1 - el resto de probabilidades
pf3 = 1 - (pf1 + pf2)

df2_test['prob_1'] = pf1
df2_test['prob_2'] = pf2
df2_test['prob_3'] = pf3

print(df2_test)

    x1   x2   x3   x4  clase        prob_1        prob_2        prob_3
0  4.6  3.2  1.4  0.2      1  1.000000e+00  1.657401e-10  1.110223e-16
1  5.3  3.7  1.5  0.2      1  1.000000e+00  2.809821e-10  1.110223e-16
2  5.7  4.4  1.5  0.4      1  1.000000e+00  8.485566e-17  0.000000e+00
3  5.0  3.5  1.6  0.6      2  1.000000e+00  1.260523e-15  1.110223e-16
4  5.5  2.5  4.0  1.3      2  2.637367e-10  1.000000e+00  0.000000e+00
5  5.7  3.0  4.2  1.2      2  5.398446e-12  1.000000e+00  0.000000e+00
6  5.7  2.8  4.1  1.3      3  2.801797e-10  1.000000e+00  1.110223e-16
7  5.8  2.7  5.1  1.9      3  2.742053e-21  4.343567e-09  1.000000e+00
8  6.3  2.5  5.0  1.9      3  6.520509e-26  3.100338e-12  1.000000e+00
9  5.9  3.0  5.1  1.8      3  3.869177e-20  9.579454e-08  9.999999e-01


In [ ]:
# Podemos ver que siempre hay una de las clases con practicamente el 100% de probabilidad (aunque en ocasiones no es la correcta)

## 3.2.2 Evaluar el rendimiento del clasificador en dicho conjunto.

### 3.2.2.4 Sensibilidad





In [35]:
# Calcula las etiquetas predichas (clase con la probabilidad más alta)
predicted_labels = df2_test[['prob_1', 'prob_2', 'prob_3']].idxmax(axis=1).apply(lambda x: int(x[-1]))

# Calcula las etiquetas verdaderas
true_labels = df2_test['clase']

# Calcula la matriz de confusión
confusion_matrix = pd.crosstab(true_labels, predicted_labels)

# Calcula la sensibilidad (tasa de verdaderos positivos) para cada clase
sensitivity_class1 = confusion_matrix.loc[1, 1] / (confusion_matrix.loc[1, 1] + confusion_matrix.loc[1, 2] + confusion_matrix.loc[1, 3])
sensitivity_class2 = confusion_matrix.loc[2, 2] / (confusion_matrix.loc[2, 1] + confusion_matrix.loc[2, 2] + confusion_matrix.loc[2, 3])
sensitivity_class3 = confusion_matrix.loc[3, 3] / (confusion_matrix.loc[3, 1] + confusion_matrix.loc[3, 2] + confusion_matrix.loc[3, 3])

print("Sensibilidad (clase 1):", sensitivity_class1)
print("Sensibilidad (clase 2):", sensitivity_class2)
print("Sensibilidad (clase 3):", sensitivity_class3)

Sensibilidad (clase 1): 1.0
Sensibilidad (clase 2): 0.6666666666666666
Sensibilidad (clase 3): 0.75


In [39]:
predicted_labels

0    1
1    1
2    1
3    1
4    2
5    2
6    2
7    3
8    3
9    3
dtype: int64

### 3.2.2.2 FPRate

In [36]:
total_negatives = confusion_matrix.loc[2:3, 1:3].values.sum()

# Calcula el False Positive Rate (FPR) para cada clase
fpr_class1 = confusion_matrix.loc[2, 1:3].sum() / total_negatives
fpr_class2 = confusion_matrix.loc[3, 1:3].sum() / total_negatives
fpr_class3 = confusion_matrix.loc[1, 2:3].sum() / total_negatives

print("False Positive Rate (clase 1):", fpr_class1)
print("False Positive Rate (clase 2):", fpr_class2)
print("False Positive Rate (clase 3):", fpr_class3)

False Positive Rate (clase 1): 0.42857142857142855
False Positive Rate (clase 2): 0.5714285714285714
False Positive Rate (clase 3): 0.0


### 3.2.2.3 Especifidad

In [37]:
specificity_class1 = (confusion_matrix.loc[2:3, 2:3].values.sum()) / (confusion_matrix.loc[2:3, 1:3].values.sum())
specificity_class2 = (confusion_matrix.loc[[1, 3], [1, 3]].values.sum()) / (confusion_matrix.loc[[1, 3], [1, 2, 3]].values.sum())
specificity_class3 = (confusion_matrix.loc[1:2, 1:2].values.sum()) / (confusion_matrix.loc[1:2, 1:3].values.sum())


print("Especificidad (clase 1):", specificity_class1)
print("Especificidad (clase 2):", specificity_class2)
print("Especificidad (clase 3):", specificity_class3)

Especificidad (clase 1): 0.8571428571428571
Especificidad (clase 2): 0.8571428571428571
Especificidad (clase 3): 1.0


### 3.2.2.4 Precision

In [38]:
precision_class1 = confusion_matrix.loc[2, 2] / confusion_matrix.loc[:, 2].sum()
precision_class2 = confusion_matrix.loc[3, 3] / confusion_matrix.loc[:, 3].sum()
precision_class3 = confusion_matrix.loc[1, 1] / confusion_matrix.loc[:, 1].sum()

print("Precisión (clase 1):", precision_class1)
print("Precisión (clase 2):", precision_class2)
print("Precisión (clase 3):", precision_class3)

Precisión (clase 1): 0.6666666666666666
Precisión (clase 2): 1.0
Precisión (clase 3): 0.75


### 3.2.2.5 F - Score

In [41]:
# Calcula el F-Score para cada clase
f_score_class1 = 2 * (precision_class1 * sensitivity_class1) / (precision_class1 + sensitivity_class1)
f_score_class2 = 2 * (precision_class2 * sensitivity_class2) / (precision_class2 + sensitivity_class2)
f_score_class3 = 2 * (precision_class3 * sensitivity_class3) / (precision_class3 + sensitivity_class3)

print("F-Score (clase 1):", f_score_class1)
print("F-Score (clase 2):", f_score_class2)
print("F-Score (clase 3):", f_score_class3)

F-Score (clase 1): 0.8
F-Score (clase 2): 0.8
F-Score (clase 3): 0.75


## 3.2.3 Comparar el modelo obtenido con el expuesto en la lección 3.

In [ ]:
# No entiendo a que se refiere con el modelo expuesto en la leccion 3